### PR TITLE
Display pieces on board as text with color and type

### PR DESCRIPTION
**Pull request by jamesfoster85**
Added a 'color' method to the piece model.
Changed styling of squares from black/white to light gray/white.
Added logic to the view so that, while drawing each square, if a piece occupies that square it ~~writes the color and type of that piece ('White Knight', 'Black Queen', etc.)~~ displays an image of the piece's type and color.

### CODE REVIEW

**Comment by lasley** [comment]
Excellent choice using vectors

**Comment by lasley** [comment]
FYI, you can change colors dynamically with JS - http://stackoverflow.com/questions/9872947/changing-svg-image-color-with-javascript - maybe remove the duplicates?

**Comment by lasley** [comment]
:+1: - let me know if you want to explore the JS, otherwise I'll merge

**Comment by jamesfoster85** [comment]
I'd say go ahead and merge, maybe we can put the JS bit on the backlog?  It's definitely something I want to explore but it feels like a nice-to-have more than a must-have.

**Comment by lasley** [comment]
Sounds like a good plan

**Pull request merged**
