### PR TITLE
Moved validation from check? to accessible_squares

### PR DESCRIPTION
**Pull request by jamesfoster85**
This was what I was imagining in my comment about moving the validations.
Now there's no need to validate whether a piece has been captured when calling the `check?` method, because calling `legal_moves` on a captured piece no longer raises an exception, it just returns and empty array.

### CODE REVIEW

**Comment by kenwmak** [comment]
James, after adding ```return [] unless x_position && y_position``` and removed ```if piece.x_position and piece.y_position``` didn't make all the tests pass.  There are two locations for  ```if piece.x_position and piece.y_position``` that I added before, the one causing the failing is in ```is_obstructed?``` line 97 in piece.rb.  I pushed my latest changes, if you comment out that line, tests would fail.

**Comment by jamesfoster85** [comment]
Oh okay I see that now.  Yeah I didn't notice that you had already added the validation to `is_obstructed?`.  I just meant to take the one that was inside the `check?` logic and move it to `accessible squares`

**Comment by kenwmak** [comment]
Are you okay with the validation I added in ```is_obstructed?``` as is or you think it can be combined with yours?

**Comment by jamesfoster85** [comment]
I think we should have both.

**Comment by jamesfoster85** [comment]
I'm closing this request since the changes have already been made in the check_logic branch.

**Pull request closed without merging**
