### PR TITLE
Add pieces controller, edit and update actions

### PR DESCRIPTION
**Pull request by jamesfoster85**
On the game show page, each piece now links to an edit page for that piece.  The edit page appears similar to the game show page, except that all of the squares are links, which go to the update action on the pieces controller, updating the x and y positions of the piece.
 
This is extremely rough functionally, in that there are no validations for if the piece belongs to the current player or if the move is valid, it does not incorporate capturing, etc.  Wanted to get something up for people to see.  I'm curious if the way that I set up the edit/update actions here is going to meet our needs.

Also it isn't DRY, I definitely repeated myself, but again I want to make sure this approach will fit the project before I go back and refactor.

### CODE REVIEW

**Comment by lasley** [comment]
It seems like this approach will work. @deepruby/deepruby - anyone have thoughts?

**Comment by lasley** [comment]
@jamesfoster85 - I'd say everyone's good with it. You want to refactor before merge?

**Comment by lasley** [comment]
Or is this included in #21? I think I'm confused

**Comment by lasley** [comment]
Nvm, included. 

Make sure to tag related PRs, and close ones that you own if you open another that should be merged independently. If they are dependent, notate the ones that it depends on (and the order in which they need to be merged, because that can totally change things).

**Comment by jamesfoster85** [comment]
You were correct to close this.  Nin and I merged the relevant code into #21 already.

**Pull request closed without merging**
