### PR TITLE
Added Deteremine Check Logic

### PR DESCRIPTION
**Pull request by kenwmak**
* Added ```check?``` method to determine if a player is in check
* It grabs all the ```legal_moves``` of opponent's pieces into an array and check if player's king's position is included in the array
* Since captured pieces have nil positions, added validation when looping through all the pieces in the game.

### CODE REVIEW

**Comment by jamesfoster85** [comment]
Good call on the validation.  I think we should consider moving it somewhere more primary, like the `accessible_squares` method perhaps, since `check?` is probably not the only situation where someone might try to call a method on a captured piece.

A couple other things to consider:
- Could we move `check?` from being a Game method to a King method, since it is the king that is in check?  That way the method wouldn't need to take the `player_id` argument, because it would be one of the attributes of `self`, and we wouldn't need to create the local variable `king` since this would be equivalent to `self`.  And we would still be able to access the game through `self.game`
- Is it necessary to first make an array of all of the opponents legal moves and then check if the king is on the list?  Couldn't we instead have a method that returns true as soon as it finds a single piece that threatens the king?
-  It isn't strictly necessary to only check the opponent's moves, because the `legal_moves` list for a player's own pieces will never include the player's own king (thanks to `accessible_squares`).  Of course, there's a benefit to only calling the method 16 times as opposed to 32...

**Comment by kenwmak** [comment]
By validation, I was referring to the ```if piece.x_position && piece.y_position``` line. I'm not sure what you mean by moving it to ```accessible_squares``` The problem appears when doing a loop for ```game.pieces.each``` and if the x/y position are nil, it was giving me an error in the math operations I believe in ```vector_to()```

First bullet point:
I actually had a dilemma of where to put ```check?``` in King or Game model. Same situation for castling as well (after I completed it). After I put castling in the King model, I realized when I called it in the controller or view (to add a button in UI for castling), the controller needs to get the King object first. However, the Game object is already defined in the controller, so that's why I think putting ```check?``` in Game model would be easier to access from controller/view perspective.

Initially, I implemented ```check?``` without needing player_id as argument and just grab ```current_user.id```

After thinking about this some more, the current code right now already needs to define the King object in the controller because of castling, so I think we should keep it consistent of either putting ```check?``` in King model or move castling into Game model. 

Second bullet point:
That's a good point, I can make it more efficient by stopping the loop when it finds any opponent piece that can capture the king.

Third bullet point:
I don't understand what you mean here, can you explain it more? I'm using ```legal_moves``` to get the possible squares able to be made by the opponent (loop through opponent's pieces) Are you saying I need to check something else too?

**Comment by jamesfoster85** [comment]
PR #26 addresses my concern about where to have the validation.

As for my third point, what you have is great.  I was just noting that you would get the same result if you looped through all of the pieces, so you could, if you wanted to, skip the step of figuring out which ones are the opponents pieces.  I'm not saying you would want to do that, as you would then have to loop through 32 pieces instead of 16.

Also, since you are simply combining all the individual legal_moves arrays, I believe you could replace

```
piece.legal_moves.each do |square|
  opponent_moves.push(square)
end
```
with
```
opponent_moves.concat(piece.legal_moves)
```

**Comment by kenwmak** [comment]
Ahh ok, I see your PR#26.

Not sure if you have any additional feedback on my comment regarding castling and check methods' location, but we can talk more when we pair program.

**Comment by lasley** [comment]
@kenwmak & @jamesfoster85  - The pair programming is Sat yeah? Should I hold off on this and #26 until then?

**Comment by lasley** [comment]
Also awesome job collaborating guys!!!

**Comment by kenwmak** [comment]
Yeah, hold off on this, I'm likely going to change something.

**Comment by kenwmak** [comment]
I still need to make an optimization, so hold off pulling this still.

**Comment by kenwmak** [comment]
David, this pull request is ready now.

**Comment by lasley** [comment]
I almost feel like I'm copping out by not adding any review notes, but this is :+1:  fosho!

**Pull request merged**
